### ISSUE TITLE
Open source TODO

### ISSUE THREAD

**Issue by radex** [Nozbe/zacs#1]
TODOs for me:

- [ ] Add proposal for ZACS stage 2
- [ ] Document troubleshooting

TODOs for the community:

- [ ] Set up CI and code coverage
- [x] Create an example app

**Comment by radex** [comment]
@mobily great! ❤️ I think it will be easiest if I push Flow types so you know what sort of shapes the methods have :)

**Comment by mobily** [comment]
awesome @radex, I'm looking forward to it!

**Comment by radex** [comment]
@mobily Flow types are in: https://github.com/Nozbe/zacs/blob/master/src/index.js.flow

go for it!

**Comment by leiteszeke** [comment]
@radex I'm generating an example project using it, but I could see that Image is not implemented for React Native, it's for any particular reason? I read the source code and check to add it, but how do you build the source code I could not found some webpack configuration or anything else?
